apiVersion: v1
kind: Service
metadata:
  name: nodetest2-www
spec:
  type: NodePort
  selector:
    app: nodetest2-www
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodetest2-api
spec:
  type: NodePort
  selector:
    app: nodetest2-api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
